import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"
import { CartProvider } from "@/components/cart/cart-context"
import Footer from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="overflow-x-hidden scroll-smooth">
      <body className={inter.className}>
        <CartProvider>
          <div className="">
            <div className="min-h-screen">
              <Navbar />
              {children}
            </div>
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  )
}
